### ISSUE TITLE
Response to `/scans - GET` should contain all the request parameter

### ISSUE THREAD

**Issue by mlincett** [WIPACrepo/SkyDriver#39]
Currently a `GET` to `/scans` reports only the `event_id` and the `scan_ids` list, so there is no confirmation that the other arguments (`run_id`, `is_real_event`, `include_deleted`) have been correctly parsed.

The response should contain all the parameters of the request that are needed to qualify the response itself.

**Comment by ric-evans** [comment]
Great point :+1:

**Comment by mlincett** [comment]
Since we are at it, can we return deleted scans under a separated key?

**Comment by ric-evans** [comment]
> Since we are at it, can we return deleted scans under a separated key?

How about this for the schema:
```
{
    "event_id": event_id,
    "scan_ids": scan_ids,  # list of strings
    "deleted_scan_ids": scan_ids,  # list of strings
    "query": <dict of all the query args>
}
```

**Comment by ric-evans** [comment]
I can also add the `"query"` key to all the other routes/methods

**Comment by mlincett** [comment]
> > Since we are at it, can we return deleted scans under a separated key?
> 
> How about this for the schema:
> 
> ```
> {
>     "scan_ids": scan_ids,  # list of strings
>     "deleted_scan_ids": scan_ids,  # list of strings
>     "query": <dict of all the query args>
> }
> ```
> 
> I suppose we don't need `include_deleted` since they'd be included regardless

This could work but I would prefer a table-like structure where for each scan_id I have a tuple in the form `(scan_id, is_real_event, is_deleted)`, then it is easy to filter downstream. A timestamp would also be helpful.

If we do this column-wise (i.e. a dictionary of lists) then it's trivial to parse it to a dataframe or to any other table container.

**Comment by ric-evans** [comment]
How about a list of dictionaries?

**Comment by mlincett** [comment]
I guess this is the native database format? It can work as well since for all practical purposes it can be easily parsed to a dataframe.

**Comment by ric-evans** [comment]
Update: The response dict will have the added info but including `"query"` is actually a security issue, so that won't be present
