### ISSUE TITLE
K8s Pod Log Fetching

### ISSUE THREAD

**Issue by ric-evans** [WIPACrepo/SkyDriver#44]
Add built-in fetching for container logs, for as long as they exist in ArgoCD

**Comment by alemsh** [comment]
is there any chance this can't be used/grabbed from Loki? All pod logs are already being pushed into there

**Comment by ric-evans** [comment]
> is there any chance this can't be used/grabbed from Loki? All pod logs are already being pushed into there

Sure! I didn't know about Loki. How do I go about grabbing logs from there?
