### ISSUE TITLE
Allow to drop the event payload when retrieving a scan manifest

### ISSUE THREAD

**Issue by mlincett** [WIPACrepo/SkyDriver#45]
The `event_i3live_json_dict` field of the manifest contains the entire event payload, which has considerable size.

There are not many scenarios in which the payload needs to be inspected.

At the same time, the user may want to query SkyDriver for several manifests at once (like, when building a summary table of manifests for a given evend id).

I sugges to make the retrieval of `event_i3live_json_dict` optional.

**Comment by ric-evans** [comment]
sure thing!
