### ISSUE TITLE
Add `reco_algo` to `scan_metadata` in MANIFEST

### ISSUE THREAD

**Issue by mlincett** [WIPACrepo/SkyDriver#51]
Currently `scan_metadata` looks as follows:
```
 'scan_metadata': {'nside_progression': {'1': 12},
                   'position_variations': 1,
                   'scan_id': '84f89d54c0e14cb398c4806c8cf7d788'},
```
This does not include `reco_algo`, which is only present in the server arguments.

**Comment by ric-evans** [comment]
`scan_metadata` is completely open to whatever the Skymap Scanner wants to put there. It's a good idea. Note that `scan_metadata` is not present until the scanner supplies it #57
