### ISSUE TITLE
SplineMPE scans fail to start

### ISSUE THREAD

**Issue by mlincett** [WIPACrepo/SkyDriver#60]
Currently, scans with `SplineMPE` fail to start because the server hits the 8 GB memory limit.

This also causes an inconsistency in the database since the manifest can be retrieved from the `scan_id` but the `scan_id` does not appear in the list for that particular event. 

Example: `7ebf7b83913948e2bd12d52703ecace9`.

**Comment by ric-evans** [comment]
I'll add a REST argument to increase the server's memory request

**Comment by ric-evans** [comment]
The data inconsistency is consistent with https://github.com/WIPACrepo/SkyDriver/issues/57

**Comment by ric-evans** [comment]
Note that this was hitting a limit of `512MB`, the client workers have a default of `8GB`

**Comment by mlincett** [comment]
> Note that this was hitting a limit of `512MB`, the client workers have a default of `8GB`

Thank you. SplineMPE does not load spline tables server-side but still loads some IceTray modules to pre-process the event. It makes sense that I would use more than 512 MB but I would not expect huge consumption nevertheless.
