### ISSUE TITLE
Add user-defined keywords for simplifying result collecting

### ISSUE THREAD

**Issue by tianluyuan** [WIPACrepo/SkyDriver#69]
It would be nice to have an extra (optional) human-readable field that can be specified at runtime like a list of `keywords` and/or `comments` field. This would help with the filtering of results for later analysis and also when batch processing events.

**Comment by mlincett** [comment]
I like the idea of having keywords/tags for filtering.

And I can think of a scenario where different analyses use different styles of bookkeeping information, so we could have a field that can store a generic dictionary for that kind of purpose.

**Comment by ric-evans** [comment]
It's a good idea. I want to constrict the size of the data, since this database will be LARGE
