### ISSUE TITLE
Scan not launching condor jobs and error in tms-starter

### ISSUE THREAD

**Issue by mlincett** [WIPACrepo/SkyDriver#76]
Trying to launch a scan with SkyDriver, it seems the condor jobs are not launched (empty `clusters` list in manifest).

Logs from `tms-starter` end with the line:
```
2023-10-09T10:06:07.038683513Z terminate called after throwing an instance of 'boost::python::error_already_set'
```

**Comment by mlincett** [comment]
Example of failed scan id: `bb3308176af4ca885705c3160640877`

**Comment by mlincett** [comment]
Solved yesterday thanks to @ric-evans and @dsschult

@ric-evans do you think we still need the `htcondor` pinning?

**Comment by ric-evans** [comment]
> Solved yesterday thanks to @ric-evans and @dsschult
> 
> @ric-evans do you think we still need the `htcondor` pinning?

we don't, I'll bump it in my next update

**Comment by ric-evans** [comment]
https://github.com/WIPACrepo/SkyDriver/commit/e4f72c70ea769258c0412e6bad6dae03b9ed86f1
